### PR TITLE
Add logic to parse global program policy custom config

### PR DESCRIPTION
**Pull request by danfaizer**
This PR enables the feature for defining global program policies through configuration provided by #45 
In addition, some bash required changes and improvements have been implemented.

### CODE REVIEW

**Review by jesusfcr — COMMENTED** [review]
Looks good but I would add some example variables in README and local.env.example

**Comment by danfaizer** [comment]
Done! Some info/documentation has been added to the README and local.env.example files.
Please, let me know if you required more details or clarifications in there.

**Review by jesusfcr — DISMISSED** [review]
LGTM

**Review by jesusfcr — APPROVED** [review]
LGTM

**Pull request merged**
