### PR TITLE
Onboard dependabot workflows

### PR DESCRIPTION
**Pull request by purple-team-service-user**
Generated by https://github.com/adevinta/vulcan-cicd/actions/runs/6183679099

### CODE REVIEW

**Comment by purple-team-service-user** [comment]
Updated by https://github.com/adevinta/vulcan-cicd/actions/runs/6185343923

**Comment by purple-team-service-user** [comment]
Updated by https://github.com/adevinta/vulcan-cicd/actions/runs/6185382663

**Review by manelmontilla — APPROVED** [review]
LGTM

**Review by manelmontilla — APPROVED** [review]
LGTM

**Pull request merged**
